[tox]
envlist =
    py{39,310}-dj{32,42}
    py{310,311}-dj{32,42}
    py{312}-dj{42,52,main}
    py{313}-dj{52,main}
    py{314}-dj{52,60,main}
    docs

[testenv]
usedevelop = true
extras =
    tests
commands =
    pytest {posargs:tests} --cov=translated_fields --cov-report=term-missing
deps =
    pytest
    pytest-django
    pytest-cov
    contextvars
    dj32: Django>=3.2,<4.0
    dj42: Django>=4.2,<5.0
    dj52: Django>=5.2,<6.0
    dj60: Django>=6.0,<6.1
    djmain: https://github.com/django/django/archive/main.zip

[testenv:docs]
deps =
    Sphinx
changedir = docs
commands = make html
skip_install = true
allowlist_externals = make
